global:
  n2network:
    masterIf: ens4    # ← tu wpisz realny interfejs „default” (np. ens4)
  n3network:
    masterIf: ens4
  n4network:
    masterIf: ens4
  n6network:
    masterIf: ens5    # ← tu wpisz interfejs w sieci 192.168.50.0/24 (np. ens5/eth1)
