apiVersion: v1
kind: ServiceAccount
metadata:
  name: free5gc-installer
  namespace: 5g-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: free5gc-installer-role
  namespace: 5g-core
rules:
  - apiGroups: ["", "apps", "batch"]
    resources: ["deployments","statefulsets","daemonsets","services","configmaps","secrets","jobs","pods","endpoints","serviceaccounts"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: free5gc-installer-rb
  namespace: 5g-core
subjects:
  - kind: ServiceAccount
    name: free5gc-installer
    namespace: 5g-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: free5gc-installer-role
