apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-webhook
  namespace: admission-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admission-webhook-ns-reader
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admission-webhook-ns-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-webhook-ns-reader
subjects:
  - kind: ServiceAccount
    name: admission-webhook
    namespace: admission-system
