apiVersion: v1
kind: Namespace
metadata:
  name: admission-system
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: admission-selfsigned-issuer
  namespace: admission-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-cert
  namespace: admission-system
spec:
  secretName: webhook-tls
  issuerRef:
    name: admission-selfsigned-issuer
  commonName: webhook-svc.admission-system.svc
  dnsNames:
    - webhook-svc.admission-system.svc
    - webhook-svc.admission-system.svc.cluster.local
