apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-webhook-mutating
  annotations:
    cert-manager.io/inject-ca-from: admission-system/admission-webhook-serving-cert
webhooks:
  - name: labels-and-security.mutator.kkarczmarek.dev
    admissionReviewVersions: ["v1"]
    sideEffects: None
    reinvocationPolicy: IfNeeded
    timeoutSeconds: 10
    failurePolicy: Ignore
    matchPolicy: Equivalent
    namespaceSelector:
      matchLabels:
        admission.kkarczmarek.dev/enabled: "true"
    clientConfig:
      service:
        namespace: admission-system
        name: admission-webhook-svc
        path: /mutate
        port: 443
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments","statefulsets","daemonsets"]
