name: Build & Push Webhook

on:
  push:
    branches: [ main ]
    paths:
      - 'admission-controller/**'
      - '.github/workflows/build-webhook.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Prebuild Go (łatwiej zobaczyć błędy kompilacji)
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Go mod tidy & build
        working-directory: admission-controller
        run: |
          go mod tidy
          go build ./cmd/server

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push (container)
        uses: docker/build-push-action@v6
        with:
          context: ./admission-controller
          file: ./admission-controller/Dockerfile
          push: true
          tags: |
            ghcr.io/kkarczmarek/admission-webhook:0.1.1
            ghcr.io/kkarczmarek/admission-webhook:${{ github.sha }}
          platforms: linux/amd64
          provenance: false
